import type { Metadata } from "next";

import {
  Inter,
  Noto_Serif,
  Source_Code_Pro,
  Poppins,
  Nunito,
} from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "~/providers/theme-provider";
import { FontProvider } from "~/providers/font-provider";
import AuthProvider from "~/providers/auth-provider";
import { getUserSession } from "~/actions/auth";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["200", "400", "700", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notex: Note Sharing App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, error } = await getUserSession();

  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${poppins.variable} ${nunito.variable} ${inter.variable} ${notoSerif.variable} ${sourceCodePro.variable} font-provider relative antialiased dark:bg-neutral-950 dark:text-neutral-200`}
      >
        <AuthProvider
          initialError={error ? error.message || "unknown_error" : undefined}
          initialUser={user}
        >
          <FontProvider>
            <ThemeProvider
              disableTransitionOnChange
              enableSystem
              attribute="class"
              defaultTheme="system"
            >
              {children}
              {/* <MobileNav /> */}
            </ThemeProvider>
          </FontProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
