import type { Metadata } from "next";

import { Inter, Noto_Serif, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Logo } from "~/components/icons";

import { ThemeProvider } from "~/providers/theme-provider";
import { FontProvider } from "~/providers/font-provider";
import AuthProvider from "~/providers/auth-provider";
import { getUserSession } from "~/actions/auth";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notex: Note Sharing App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, error } = await getUserSession();

  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${inter.variable} ${notoSerif.variable} ${sourceCodePro.variable} font-provider relative antialiased dark:bg-neutral-950 dark:text-neutral-200`}
      >
        <AuthProvider
          initialError={error ? error.message || "unknown_error" : undefined}
          initialUser={user}
        >
          <FontProvider>
            <ThemeProvider
              disableTransitionOnChange
              enableSystem
              attribute="class"
              defaultTheme="system"
            >
              <header className="bg-neutral-100 px-4 py-3 md:px-8 md:py-6 lg:hidden dark:bg-neutral-800">
                <Link href="/">
                  <Logo />
                </Link>
              </header>
              {children}
              {/* <MobileNav /> */}
            </ThemeProvider>
          </FontProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
